### ISSUE TITLE
Filter for duplicate numbers

### ISSUE THREAD

**Issue by alexstyl** [alexstyl/contactstore#11]
Seems like the contact database might contain the same phone number multiple times.

Someone shared a screenshot of the sample app, where the contact details show the same number multiple times. The contact had WhatsApp linked to it. An other contact contained the same phone three times. That contact had both WhatsApp and Signal installed.

| Whatsapp | Whatsapp + Signal |
| --- | --- | 
![Frame 1](https://user-images.githubusercontent.com/1665273/148051676-fb81d71f-9710-41ef-994f-f94438747631.png) | ![Frame 2](https://user-images.githubusercontent.com/1665273/148051682-69a74116-2357-4d3a-af9b-7f8761c1098d.png) |

**Comment by rbenza** [comment]
I also came across this, some of the contacts had 8-10 times the same phone number. So requird custom logic to filter it.

**Comment by tatocaster** [comment]
Can you show the screen?
WhatsApp, Viber currently returns 3 different items - calling, video calling, and chat. Isn't that an intended behavior? Should this library return only 1 number for each chat app?

**Comment by alexstyl** [comment]
@tatocaster I have updated the first post with photos. Notice the duplicate _Phones_ you have in both photos. One Phone entry is the one the person manually added in their contacts app. The others are probably coming from the 3rd party apps.

The WhatsApp, Viber, etc work as they should, but it seems like the ContentProvider returns a duplicate of the phone number for each linked account.

I wonder how the [AOSP contacts app](https://github.com/aosp-mirror/platform_packages_apps_contacts) prevents this issue.

**Comment by tatocaster** [comment]
I see now. Interesting, I had the same issue but several years ago 👀  Will take a look on that

**Comment by alexstyl** [comment]
Quick update: Ended up picking this up. (cc @tatocaster)

I went through the AOSP and it seems like they are keeping track of the accounts for each ContentValue (phones,mails, etc). Because of that they know if a phone number belongs to an account which is editable (google). Having this information, it is easy to filter out non-editable items when not-needed (i.e. the edit screen).

I am currently working on the API design to support this nicely.

**Comment by alexstyl** [comment]
This is currently where I am at.

I am considering of having an `internetAccounts` property on the `Contact` interface. So the Contact itself holds all information about the aggregated contacts (local, google, whatsapp, etc). The InternetAccount holds information about where each information belongs. 

```kotlin
Contact {
    displayName : String
    contactId : Long
    stared :Boolean

    phones  : List<LabeledValue<PhoneNumbers>>
    mails   : List<LabeledValue<MailAddress>> 
    postals : List<LabeledValue<MailAddress>>
    // other standard properties
 
    internetAccounts : List<InternetAccount>
}
```

Each InternetAccount contains information about the account, and the data contained in that account (such as phone numbers, postals, etc)

Adding and updating contacts in accounts: 

```kotlin
contactStore.execute {
    // create a new contact into a google account
    insert {
        account = InternetAccount("com.google", "mail@gmail.com")
        phone("555", Label.Main)
    }
    
    // how to store a new number on specific account
    update(contact.mutableCopy {
        // will be stored locally
        phones.add(LabeledValue("555-123-456", Label.Main))

        linkedAccounts.first { it.accountType == "com.google" }.apply {
            // will be stored on google account
            phones.add(LabeledValue("555", Label.Main))
        }
    })
}
```

The InternetAccount name is temporary. I am thinking whether there is a need for having an 'account' for information stored locally (on the device) or the SIM card. 

Any feedback is more than welcome

**Comment by alexstyl** [comment]
After a lot of thought, I ended up keeping the API as is. In order to resolve the duplicate numbers, I have included information of each account in each `LabeledValue` (in https://github.com/alexstyl/contactstore/pull/49).

There is more work to be done for allowing storing information on specific numbers, and that will be done on a later stage.

**Comment by alexstyl** [comment]
Closing this as won't fix. 

The way to prevent any duplication on the UI is by checking the new `InternetAccount` of each `LabeledValue` and decide whether they need to use the data item or not.
