### ISSUE TITLE
Getting IMs of contacts (CommonDataKinds.Im.*)

### ISSUE THREAD

**Issue by duytuan001** [alexstyl/contactstore#18]
I want to query IM of Contacts (Telegram, Skype, LinkedIn, ...).
I think linkedAccountValues is different with IM.

**Comment by alexstyl** [comment]
Hi @duytuan001! That seems reasonable to include.

I had a look at the Im documenation. Are `EXTRA_ADDRESS_BOOK_INDEX`, `EXTRA_ADDRESS_BOOK_INDEX_COUNTS`, `EXTRA_ADDRESS_BOOK_INDEX_TITLES` important to you? I am not sure I understand their usage in an app.

**Comment by alexstyl** [comment]
Support for Im is pushed to main (https://github.com/alexstyl/contactstore/commit/1f59d6c06913ca090f6ebc9ca4cf5ea9a1f6f142) and will be available in 0.7.0

Closing as resolved

**Comment by duytuan001** [comment]
Thank you very much @alexstyl . <3
