### ISSUE TITLE
Support for a Idiomatic Kotlin API

### ISSUE THREAD

**Issue by alexstyl** [alexstyl/contactstore#2]
There are various opportunities for making developer life easier using the API.

For starters, a typical way a developer might create a new contact is:
```kotlin
        store.execute(SaveRequest().apply {
            insert(
                MutableContact().apply {
                    prefix = "A."
                    firstName = "Paolo"
                    middleName = "M."
                    lastName = "Melendez"
                    suffix = "Z."
                }
            )
        })
```
This relies on Kotlin's `apply` extension, which might hint towards embedding the lambda into the API itself. 
An example:
```kotlin
        store.execute {
            insert(newContact {
                prefix = "A."
                firstName = "Paolo"
                middleName = "M."
                lastName = "Melendez"
                suffix = "Z."
            })
        }
```
In the same fashion, updating a contact could be expressed as:
```kotlin
        store.execute {
            update(contact.mutableCopy {
                note = Note("To infinity and beyond!")
            })
        }
```
This is an idea I am still exploring. Unless there is a need/interest for a more idiomatic API, it might be just overengineering.

**Comment by alorma** [comment]
Hi! Just to give an extra point of view:

Why not do something like:

```
        store.execute {
            insert { // this is a lambda with MutableContact as a receiver
                prefix = "A."
                firstName = "Paolo"
                middleName = "M."
                lastName = "Melendez"
                suffix = "Z."
            }
        }
```

**Comment by alexstyl** [comment]
Hi @alorma. I like the idea of the receiver. 

My concern is whether having no object to pass to insert (or execute) might affect how testable the store can be. I do some experimentation and see how it works on a real app.

Thank you for the take 👍

**Comment by alorma** [comment]
No problem! I hope have time to give this a try someday soon!
