### ISSUE TITLE
📖 Guest Book

### ISSUE THREAD

**Issue by alexstyl** [alexstyl/contactstore#21]
This issue is here for you to write any nice things about the project you like. I would love to know how ContactStore has helped you in your projects. If you happen to know any companies/projects that use it, feel free to mention them.

If you have any issues, questions, suggestions, please [open a new issue](https://github.com/alexstyl/contactstore/issues/new)

Thanks,
Alex

**Comment by alexstyl** [comment]
I used ContactStore in the [Jetpack Compose Starter Kit](https://alexstyl.gumroad.com/l/compose-contacts) so that I could focus on the UI bits. 

Ended up building the whole contacts app in 2 weeks time. 🚀

**Comment by fgubler** [comment]
I am using the ContactStore for my private project which is privacy-focused contacts app:
https://github.com/fgubler/PrivateContacts

Very happy so far (both by the libarary and by your quick responses to my questions)
