### ISSUE TITLE
Ability to select CursorIndices.CONTACT_LOOKUP_KEY_INDEX

### ISSUE THREAD

**Issue by itsandreramon** [alexstyl/contactstore#22]
Since the contact IDs are not enough to uniquely identify a contact, you sometimes need to use the lookup key.

**Comment by alexstyl** [comment]
Thanks for the request @itsandreramon 

The lookup key has been pushed to main (https://github.com/alexstyl/contactstore/commit/12f4128a7a111885e145ad338fa070eff476916f) and will be available in 0.7.0.

Closing as resolved
