### ISSUE TITLE
[Suggestion] Open Wiki for everyone

### ISSUE THREAD

**Issue by tatocaster** [alexstyl/contactstore#25]
I suggest opening wiki pages free to edit for everyone and eventually the project will get better documentation. 

ref: [Github doc about wiki pages](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis)

In that specific case, I want to edit [this wiki page](https://github.com/alexstyl/contactstore/wiki/Setting-up-the-project-locally), because it lacks one line in the end to remove any confusion:
`signing.password=`

If you open it, I would happily contribute to

Thanks

**Comment by alexstyl** [comment]
Thanks for the suggestion @tatocaster. To my understanding, folks who contribute to the project automatically gain the ability to edit the wiki. 

I am hesistant of letting anyone on Github update the wiki.
