### ISSUE TITLE
Run unit tests and Android tests via Github Actions

### ISSUE THREAD

**Issue by alexstyl** [alexstyl/contactstore#29]
There are more people contributing to the project lately, and it would be nice to have less moderation required on each PR.
This issue is about running all unit tests and Android tests of all modules of the project, using Github Actions.

Requirements:
- Have all unit tests and Android tests to run when someone opens a PR.
- If any of the tests fail, then the PR should be blocked.
- Document is a way (i.e. on your PR) how this automation works.

I have to admit that I have yet to experiment with Github Actions so I am not entirely sure what it fully entails.

**There is no need for this work to take place in a single PR.**

If you would like to pick up this task, reply to this issue, so that I can assign it to you.

**Comment by alexstyl** [comment]
@tatocaster If you are interested in this, do let me know. Also, do let me know if I can help out in any way.

**Comment by tatocaster** [comment]
Already working on it and will submit PR in a few hours with the documentation how to setup project settings as an admin as well 🚀

**Comment by tatocaster** [comment]
I guess this issue can be closed. There still is the room for improvement in the current workflow but that's for another issue 👀
