### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by arunkr83** [alexstyl/contactstore#33]
Can any one share the java version to get the contact list, edit contact and add contact .? Thanks

**Comment by alexstyl** [comment]
Hi @arunkr83! Contact Store is a Kotlin API. Java is not currently suppoted to keep development lean.

Are you looking for a Java version of Contact Store or asking how to do such operations using the original Android API? Maybe I can help out if I understand better what you are trying to do.

**Comment by arunkr83** [comment]
> Hi @arunkr83! Contact Store is a Kotlin API. Java is not currently suppoted to keep development lean.
> 
> Are you looking for a Java version of Contact Store or asking how to do such operations using the original Android API? Maybe I can help out if I understand better what you are trying to do.

       how to do operations in java .?

**Comment by alexstyl** [comment]
@arunkr83 Using Contact Store from Java is not currently supported. 

Even though it should be technically possible to use Contact Store in Java, I do not think that it is trivial to do.

**Comment by alexstyl** [comment]
Noted that Java intergration has been requested. Closing this for now.
