### ISSUE TITLE
java.lang.NullPointerException: item.getAsString(NameColumns.MIDDLE_NAME) must not be null

### ISSUE THREAD

**Issue by kopylovis** [alexstyl/contactstore#60]
Hi,
Got this when I selected a contact with no middle name in sample app.

I think these properties should be null-safety in ContactQueries.

firstName = item.getAsString(NameColumns.GIVEN_NAME)
middleName = item.getAsString(NameColumns.MIDDLE_NAME)
lastName = item.getAsString(NameColumns.FAMILY_NAME)
prefix = item.getAsString(NameColumns.PREFIX)
suffix = item.getAsString(NameColumns.SUFFIX)
phoneticFirstName = item.getAsString(NameColumns.PHONETIC_GIVEN_NAME) 
phoneticMiddleName = item.getAsString(NameColumns.PHONETIC_MIDDLE_NAME)
phoneticLastName = item.getAsString(NameColumns.PHONETIC_FAMILY_NAME)

**Comment by alexstyl** [comment]
hi @kopylovis. Thanks for the report.

Seems like a straightforward fix. I'm on it

**Comment by alexstyl** [comment]
This is issue has been patched and is now available in 1.2.2

Closing as fixed.
