### ISSUE TITLE
Feature Request: Provide Paging-Support

### ISSUE THREAD

**Issue by fgubler** [alexstyl/contactstore#66]
When you have a lot of contacts, loading them all at once can take some time. For that reason, I would like to use paging.
Therefore it would be really nice if a method could be provided which may look a bit like this:

```
    public fun fetchContactsPaged(
        predicate: ContactPredicate? = null,
        columnsToFetch: List<ContactColumn> = emptyList(),
        displayNameStyle: DisplayNameStyle = DisplayNameStyle.Primary,
        pageSize: Int,
        offset: Int,
    ): FetchRequest<List<Contact>>
```
allowing the caller to pass a page size (how many records should be fetched) and an offset (assuming the contacts are sorted by displayName).

**Comment by alexstyl** [comment]
Thanks for the feature request. Could you kindly share some numbers? What is the number of contacts you are trying to process?

**Comment by fgubler** [comment]
Thanks for the reply :-).
Of course: My test data-set were around 500-600 contacts which took around 12s to load on my test-device.
The query I sent asked for the Name-columns.

For context: I am currently using my old phone (Android 7) for development so part of the "long" duration is surely due to old hardware but still, showing a loading screen to the user for 12s is not ideal :-).
If it helps, I can also test it on newer devices to get some more data-points.

**Comment by alexstyl** [comment]
12s is really not good. Any chance you can give me the specs of the device?

**Comment by fgubler** [comment]
Sure thing
- It is a Sony Xperia Z5 Compact (E5823), Snapdragon 810 (8-core), 2GB RAM, Android 7.1.1 => 12s
- Newer device 1: Sony Xperia XZ2 Compact (E8324), Snapdragon 845 (8-core), 4 GB RAM, Android 10 => 4.6s - 5s
- Newer device 2: Samsung Galaxy S22 => 9s

So in conclusion: there seem to be large differences between the devices and some of them quite unexpected
(strange that the much newer S22 would be slower than the Sony one which is around 3.5 years old)

**Comment by fgubler** [comment]
Just noticed something: If I just do a plain `fetch()` without the `columnsToFetch = listOf(ContactColumn.Names)`, performance is now issue at all: around 400ms instead of 12s for the oldest device

**Comment by fgubler** [comment]
Yes that is the case and makes sense.
Yes it is for the contact-list screen, so I will avoid ContactColumn.Names and just use displayname, thanks 👍 
I anyway load the details for the detail-screen later when I just have to do it for 1 contact. I just thought, I needed the Names from the beginning.

That should solve the problem: thanks a lot for the help :-).

PS: in case you were wondering, my use-case is this: https://github.com/fgubler/PrivateContacts

**Comment by fgubler** [comment]
Thanks for the help 😃. Works like a charm, now.
