### ISSUE TITLE
Feature Request: Allow passing multiple predicates

### ISSUE THREAD

**Issue by fgubler** [alexstyl/contactstore#67]
It would be great if there was a `fetchContacts()` method allowing the caller to pass multiple predicates. Or an additional predicate which searches over all fields of the contact.

**Comment by alexstyl** [comment]
thanks for the feature request. is there a specific usecase you are after which cannot work with ContactStore right now?

**Comment by fgubler** [comment]
Thanks for the quick reply :-)
(and first of all thanks for the nice library: I was really not looking forward to write all that access-logic myself before I found it)

My use case is a "standard" free-text search field over a contact-list: I basically want to compare the query to "all" fields of the contact and see if there is a match. After all, the user could be searching for name, email, phone, etc..

I could ofc just call `fetchContacts()` for each of the possible predicates but I guess a single call would be faster (as in better runtime performance).

Does that make sense?

**Comment by alexstyl** [comment]
thanks for the details. Can you try using `fetchContacts()` using the `ContactPredicate.NameLookup` passing the query you need? I need a quick test and I think that it would work for your usecase

**Comment by fgubler** [comment]
Thanks a lot: that actually does seem to work perfectly ❤.
Maybe a different naming or some KDoc would help? (so people will not bother you with the same question in the future :-))
BTW: with the filtering, the performance is above reproach (as expected, only having to transmit something like 1-5 contacts makes a big difference)

**Comment by alexstyl** [comment]
That's good news! There was some confusion with the official documentation as it says the filter is used for contact names which doesn't seem right. I'll address that with a proper name asap :) 

Regarding the performance, I believe it is very related to your other issue so we'll takle it there.

Keeping this issue open until the naming is merged

**Comment by alexstyl** [comment]
This is now merged to `main`. It will be available in 1.4.0 without breaking changes. Closing as done
