### ISSUE TITLE
Problem with ContactGroups when moving a contact between two accounts

### ISSUE THREAD

**Issue by fgubler** [alexstyl/contactstore#74]
Hi

I have encountered an interesting problem this weekend: 
- My app can now move/copy a contact from my separate DB to the "normal" Contact-Store. But as that would require a deeper understanding of my usecase, let us instead assume I want to move the contact from one Account (as in InternetAccount) to another. The behavior should be the same.
- Part of my new logic takes care of copying the GroupMemberships. To be safe - I check that all the GroupMemberships which I want to copy, reference a valid ContactGroup. 
- I use `contactStore.fetchContactGroups()` to load all existing ContactGroups to compare them by id (and name as fallback). But the problem is that - if I understood it correctly - that is an aggregated list over **all** accounts on the phone. 
- In my case, that is not what I want, because while a ContactGroup **does** exist on the phone, it may **not** exist in the account into which I am copying the contact. As a result, the GroupMembership is set correctly but in the new account, it does not reference any valid ContactGroup and is therefore not shown in the default Google Contacts app.
- However, if I move the contact back, everything is fine again because the GroupMembership survived and now references a valid ContactGroup again.

Does that description make any sense?

If yes, I have two questions / wishes
1. Would it be possible to add the option to filter `contactStore.fetchContactGroups()` by Account?
2. When using `contactStore.execute { insertGroup(myGroup) }` where is it actually saved? Into the phone's local contacts? Into all the accounts? Into the "default" account? 
=> would be great if it were able to specify exactly into which account to store it

**Comment by alexstyl** [comment]
thanks for the feature request @fgubler and the detailed issue.

> Would it be possible to add the option to filter contactStore.fetchContactGroups() by Account?
I will have a look into this and let you know. If it is something supported by Android i would be more than happy to support it.

> When using contactStore.execute { insertGroup(myGroup) } where is it actually saved?
I think it is the phone's (offline), if it follows what saving a contact does without specifying an account

> would be great if it were able to specify exactly into which account to store it
seems reasonable. i will need to have a look how it is done from android's side first and will let you know.

**Comment by fgubler** [comment]
Thanks a lot 😍

**Comment by alexstyl** [comment]
Just pushed this to [1.6.0](https://github.com/alexstyl/contactstore/releases/tag/1.6.0). 

The way to insert a new group into a specific account is:

```kotlin
contactStore.execute {
      insertGroup(intoAccount = InternetAccount(...)) {
          title = "My Group"
      }
  }
```

to update a group you can:
```kotlin
val updatedCopy = group.mutableCopy {
    note = "Updated Note"
    title = "Updated Title"
    account = InternetAccount("test@test.com", "test.com")
}
contactStore.execute {
    updateGroup(updatedCopy)
}
```

I will close this issue once the new version is available on maven

**Comment by alexstyl** [comment]
This is now live in [1.7.0](https://github.com/alexstyl/contactstore/releases/tag/1.7.0).

Now the contact groups you fetch are going to include an `account` property that contains information about which account the contact group is saved into. a null account means the group is stored locally (offline).

Closing this as it is now live

**Comment by fgubler** [comment]
Great, thank youbl so much :-)
I will try it as soon as I get back from vacation.

**Comment by fgubler** [comment]
Seems to work splendidly, thanks :-)
